name: Firebase Distribution Action
description: Deploy to Firebase Distribution
inputs:
  GITHUB_REF_NAME:
    required: true
    description: GITHUB_REF_NAME
runs:
  using: "composite"
  steps:
    - name: GitFlow Event
      env:
        GITHUB_REF_NAME: ${{inputs.GITHUB_REF_NAME}}
      shell: bash
      run: cd .shelltool && make gitflow_event
    - name: Installing node
      uses: actions/setup-node@v1
    - name: Install React Native CLI
      shell: bash
      run: cd .. && yarn global add react-native-cli
    - name: Install yarn dependencies
      shell: bash
      run: yarn install
